#!/usr/bin/env python3
"""Build a compact STANDALONE HTML file (for the email attachment).

Unlike the Gmail email body (inline CSS, no <style>), this file is meant to be
opened in a browser — so it uses a normal <style> head and is much smaller.
Its links are the DIRECT article URLs (Dataxet proxy stripped for online/social),
so clicking from the opened file bypasses Gmail's google.com/url wrapper entirely
(docs/PRD.md BR-09).

Usage: build_standalone.py --input digest_config.json --date "24 มิถุนายน 2569" \
       --date-en "June 24, 2026" --output Sansiri-News-2026-06-24.html
"""
import argparse
import html
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import unwrap_dataxet


def esc(s):
    return html.escape(s or "", quote=True)


def links(urls):
    out = []
    for k in ("prints", "online", "social"):
        for u in urls.get(k, []):
            out.append(f'<a href="{esc(unwrap_dataxet(u["headline_url"]))}" '
                       f'target="_blank" rel="noopener">{esc(u["media_title"])}</a>')
    return " · ".join(out)


def best_url(urls):
    for k in ("prints", "online", "social"):
        if urls.get(k):
            return unwrap_dataxet(urls[k][0]["headline_url"])
    return "#"


def items(clusters):
    rows = []
    for c in clusters:
        title = esc(c.get("title") or c.get("suggestion_title"))
        summ = esc(c.get("summary")).replace("\n\n", "<br><br>")
        rows.append(
            f'<div class="item"><a class="hl" href="{esc(best_url(c["urls"]))}" '
            f'target="_blank" rel="noopener">{title}</a>'
            f'<div class="src">{links(c["urls"])}</div>'
            f'<p>{summ}</p></div>')
    return "\n".join(rows)


def build(cfg, date_th, date_en):
    return f"""<!DOCTYPE html>
<html lang="th"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Sansiri News — {esc(date_en)}</title>
<style>
  body{{font-family:'GraphikTH','Segoe UI',Tahoma,Helvetica,Arial,sans-serif;color:#000;margin:0;background:#fff;line-height:1.6}}
  .wrap{{max-width:760px;margin:0 auto}}
  .ai{{background:#D4A843;color:#1B3A5C;font-size:11px;font-weight:600;letter-spacing:.4px;padding:6px 24px}}
  .hdr{{background:#1B3A5C;color:#fff;padding:24px}}
  .hdr h1{{margin:0 0 6px;font-size:22px}} .hdr .sub{{color:#cfd8e3;font-size:13px}}
  .body{{padding:24px}}
  h2{{color:#0563C1;font-size:16px;border-bottom:3px solid #D4A843;padding-bottom:6px;margin:24px 0 14px}}
  .item{{margin:0 0 22px}}
  .hl{{font-size:15px;font-weight:bold;color:#000;text-decoration:none}} .hl:hover{{text-decoration:underline}}
  .src{{font-size:13px;margin:4px 0 6px}} .src a{{color:#0563C1}}
  .item p{{font-size:14px;margin:0}}
  .foot{{padding:18px 24px;font-size:14px;border-top:1px solid #eee}}
</style></head>
<body><div class="wrap">
<div class="ai">&#10022; Generated by AI + Automation Tool &nbsp;|&nbsp; Developed by PR Team, Sansiri</div>
<div class="hdr"><h1>Sansiri News</h1><div class="sub">Sansiri News: Top Stories &amp; Competitor Moves | {esc(date_en)}</div></div>
<div class="body">
<p>ข่าวเกี่ยวกับกลุ่มบริษัทแสนสิริ ข่าวคู่แข่งและอสังหาทั่วไป &nbsp;วันที่ &nbsp;{esc(date_th)} &nbsp;&nbsp;มีรายละเอียดที่น่าสนใจดังนี้</p>
<h2>ข่าวกลุ่มบริษัทแสนสิริ</h2>
{items(cfg["sansiri"])}
<h2>ข่าวคู่แข่งและอสังหาทั่วไป</h2>
{items(cfg["competitor"])}
</div>
<div class="foot">ฝ่ายสื่อสารองค์กร<br>บริษัท แสนสิริ จำกัด (มหาชน)</div>
</div></body></html>"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="digest_config.json")
    ap.add_argument("--date", required=True)
    ap.add_argument("--date-en", required=True)
    ap.add_argument("--output", required=True)
    args = ap.parse_args()
    with open(args.input, encoding="utf-8") as fh:
        cfg = json.load(fh)
    out = build(cfg, args.date, args.date_en)
    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write(out)
    print(f"OK: standalone -> {args.output} ({len(out.encode('utf-8'))} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
