#!/usr/bin/env python3
"""C-05 HTML Builder — render digest_config.json into the branded Gmail email.

Pipeline step 5 (docs/Techspec.md §4, uxui.md UX-07). Inline CSS only, GraphikTH
stack, table layout (no <style>, no Noto Sans Thai). Headline anchors are bold &
unstyled; source links ordered print -> online -> social with bare outlet names.

Exit code: 0 ok · 2 config incomplete (empty title/summary).

Usage:
    build_html_digest.py --input digest_config.json \
        --date "24 มิถุนายน 2569" --date-en "June 24, 2026" \
        --output digest_20260624.html
"""
import argparse
import html
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import unwrap_dataxet

NAVY, GOLD, LINK = "#1B3A5C", "#D4A843", "#0563C1"
FONT = "'GraphikTH','Segoe UI',Tahoma,Helvetica,Arial,sans-serif"
SEC_SANSIRI = "ข่าวกลุ่มบริษัทแสนสิริ"
SEC_COMPETITOR = "ข่าวคู่แข่งและอสังหาทั่วไป"
FOOTER = "ฝ่ายสื่อสารองค์กร<br>บริษัท แสนสิริ จำกัด (มหาชน)"


def esc(s):
    return html.escape(s or "", quote=True)


def best_url(urls):
    for k in ("prints", "online", "social"):
        if urls.get(k):
            return unwrap_dataxet(urls[k][0]["headline_url"])
    return "#"


def source_links_row(urls):
    parts = []
    for k in ("prints", "online", "social"):  # print -> online -> social
        for u in urls.get(k, []):
            href = unwrap_dataxet(u["headline_url"])
            parts.append(
                f'<a href="{esc(href)}" '
                f'style="color:{LINK};text-decoration:underline;">'
                f'{esc(u["media_title"])}</a>'
            )
    return "&nbsp;&nbsp;".join(parts)


def render_item(c):
    bu = esc(best_url(c["urls"]))
    title = esc(c.get("title") or c.get("suggestion_title"))
    summary = esc(c.get("summary"))
    return f"""
  <p style="margin:0 0 4px 0;font-size:15px;font-weight:bold;line-height:1.5;font-family:{FONT};">
    <a href="{bu}" style="color:#000000;text-decoration:none;font-weight:bold;">{title}</a></p>
  <p style="margin:0 0 6px 0;font-size:13px;line-height:1.5;font-family:{FONT};">
    {source_links_row(c["urls"])}</p>
  <p style="margin:0 0 24px 0;font-size:14px;color:#000000;line-height:1.7;font-family:{FONT};">{summary}</p>"""


def render_section(title, clusters):
    items = "".join(render_item(c) for c in clusters)
    return f"""
  <p style="margin:0;padding:0;font-size:16px;font-weight:bold;color:{LINK};font-family:{FONT};">{title}</p>
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:4px 0 18px 0;">
    <tr><td style="border-top:3px solid {GOLD};font-size:0;line-height:0;height:1px;">&nbsp;</td></tr></table>
{items}"""


def web_link_row(url):
    """Footer link to the standalone web version (clean, direct article links)."""
    if not url:
        return ""
    return f"""
<tr><td style="padding:0 24px 20px 24px;">
  <p style="margin:0;font-size:12px;color:#777777;font-family:{FONT};">&#128279; <a href="{esc(url)}" style="color:{LINK};text-decoration:underline;">เปิดเวอร์ชันเว็บ (คลิกลิงก์ข่าวได้โดยตรง สำหรับตรวจสอบ)</a></p>
</td></tr>"""


def build(cfg, date_th, date_en, web_link=""):
    intro = (f"ข่าวเกี่ยวกับกลุ่มบริษัทแสนสิริ ข่าวคู่แข่งและอสังหาทั่วไป "
             f"&nbsp;วันที่ &nbsp;{esc(date_th)} &nbsp;&nbsp;มีรายละเอียดที่น่าสนใจดังนี้")
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background-color:#ffffff;font-family:{FONT};font-size:14px;color:#000000;">
<table width="100%" cellpadding="0" cellspacing="0" border="0">

<tr><td bgcolor="{GOLD}" style="background-color:{GOLD};padding:6px 24px;">
  <p style="margin:0;font-size:11px;color:{NAVY};font-weight:600;font-family:{FONT};letter-spacing:0.4px;">&#10022; Generated by AI + Automation Tool &nbsp;|&nbsp; Developed by PR Team, Sansiri</p>
</td></tr>

<tr><td bgcolor="{NAVY}" style="background-color:{NAVY};padding:28px 24px 22px 24px;">
  <p style="margin:0 0 6px 0;font-size:22px;font-weight:bold;color:#ffffff;font-family:{FONT};">Sansiri News</p>
  <p style="margin:0;font-size:13px;color:#cfd8e3;font-family:{FONT};">Sansiri News: Top Stories &amp; Competitor Moves | {esc(date_en)}</p>
</td></tr>

<tr><td style="padding:24px 24px 20px 24px;font-family:{FONT};">
  <p style="margin:0 0 24px 0;font-size:14px;color:#000000;line-height:1.6;font-family:{FONT};">{intro}</p>
{render_section(SEC_SANSIRI, cfg["sansiri"])}
{render_section(SEC_COMPETITOR, cfg["competitor"])}
</td></tr>

<tr><td style="padding:18px 24px;">
  <p style="margin:0;font-size:14px;color:#000000;font-family:{FONT};">{FOOTER}</p>
</td></tr>
{web_link_row(web_link)}
</table>
</body>
</html>"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="digest_config.json")
    ap.add_argument("--date", required=True, help="Thai date e.g. '24 มิถุนายน 2569'")
    ap.add_argument("--date-en", required=True, help="English date e.g. 'June 24, 2026'")
    ap.add_argument("--output", required=True)
    ap.add_argument("--web-link", default="", help="URL of the hosted standalone HTML; shown at the very bottom for review")
    ap.add_argument("--skip-validation", action="store_true")
    args = ap.parse_args()

    with open(args.input, encoding="utf-8") as fh:
        cfg = json.load(fh)

    if not args.skip_validation:
        for c in cfg.get("sansiri", []) + cfg.get("competitor", []):
            if not (c.get("title") or c.get("suggestion_title")) or not c.get("summary"):
                print(f"ERROR: cluster {c.get('cluster_id')} missing title/summary",
                      file=sys.stderr)
                return 2

    html_out = build(cfg, args.date, args.date_en, web_link=args.web_link)
    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write(html_out)
    n = len(cfg.get("sansiri", [])) + len(cfg.get("competitor", []))
    print(f"OK: rendered {n} items ({len(html_out)} bytes) -> {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
