#!/usr/bin/env python3
"""C-09 Failure Reporter — render a plain failure-notice HTML when the pipeline
cannot produce a digest (docs/Techspec.md §8, PRD FR-15). The skill then creates
a Gmail draft from this HTML so a failed run never goes silent.

Usage: build_failure_report.py --stage "C-02 parse" --reason "0 records" \
       --date "24 มิถุนายน 2569" --output failure_20260624.html
"""
import argparse
import html
import sys

NAVY, GOLD, FONT = "#1B3A5C", "#D4A843", "'GraphikTH','Segoe UI',Tahoma,Helvetica,Arial,sans-serif"


def build(stage, reason, date_th):
    e = html.escape
    return f"""<!DOCTYPE html><html><head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background-color:#ffffff;font-family:{FONT};font-size:14px;color:#000000;">
<table width="100%" cellpadding="0" cellspacing="0" border="0">
<tr><td style="background-color:{GOLD};padding:6px 24px;">
  <p style="margin:0;font-size:11px;color:{NAVY};font-weight:600;font-family:{FONT};">&#10022; Generated by AI + Automation Tool &nbsp;|&nbsp; Developed by PR Team, Sansiri</p></td></tr>
<tr><td style="background-color:{NAVY};padding:24px;">
  <p style="margin:0;font-size:20px;font-weight:bold;color:#ffffff;font-family:{FONT};">Sansiri News — แจ้งเตือนระบบ</p></td></tr>
<tr><td style="padding:24px;font-family:{FONT};">
  <p style="margin:0 0 12px 0;font-size:15px;font-weight:bold;color:#b00020;">ระบบไม่สามารถสร้างสรุปข่าวประจำวันได้ ({e(date_th)})</p>
  <p style="margin:0 0 8px 0;">ขั้นตอนที่ล้มเหลว: <b>{e(stage)}</b></p>
  <p style="margin:0 0 8px 0;">สาเหตุ: {e(reason)}</p>
  <p style="margin:16px 0 0 0;font-size:13px;color:#555;">กรุณาตรวจสอบอีเมล iQNewsClip ของวันนี้ และ log การทำงาน แล้วรันใหม่อีกครั้ง</p>
</td></tr>
<tr><td style="padding:18px 24px;">
  <p style="margin:0;font-size:14px;color:#000000;font-family:{FONT};">ฝ่ายสื่อสารองค์กร<br>บริษัท แสนสิริ จำกัด (มหาชน)</p></td></tr>
</table></body></html>"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stage", required=True)
    ap.add_argument("--reason", required=True)
    ap.add_argument("--date", required=True)
    ap.add_argument("--output", required=True)
    args = ap.parse_args()
    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write(build(args.stage, args.reason, args.date))
    print(f"OK: failure report -> {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
