#!/usr/bin/env python3
"""C-06 Validator — 12 deterministic checks on the digest HTML.

Pipeline step 6 (docs/Techspec.md §7, uxui.md UX-08). MUST exit 0 before the
Gmail draft is created (C-07). C9 (item count) is a warning by default because
the Content Quality Gate (PRD BR-03) may legitimately drop items below 10.

Exit code: 0 all hard checks pass · 1 one or more failed.

Usage: pre_draft_check.py digest_YYYYMMDD.html [--strict-count]
"""
import argparse
import re
import sys

FOOTER = "ฝ่ายสื่อสารองค์กร"
FOOTER2 = "บริษัท แสนสิริ จำกัด (มหาชน)"
PROHIBITED = ["(print)", "[PDF]", "(FB)", "(IG)", "(TikTok)", "อ่านเพิ่มเติม"]


def run_checks(html, strict_count=False):
    results = []  # (id, ok, is_warning, message)

    def chk(cid, ok, msg, warn=False):
        results.append((cid, ok, warn, msg))

    # C1 broken URL pattern
    chk("C1", "https://https:/" not in html and "http://https:/" not in html,
        "no broken https://https:/ URLs")
    # C2 prohibited labels
    bad = [p for p in PROHIBITED if p in html]
    chk("C2", not bad, f"no prohibited labels (found: {bad})" if bad else "no prohibited labels")
    # C3 AI banner
    chk("C3", "#D4A843" in html and "Generated by AI" in html, "AI banner present")
    # C4 main banner
    chk("C4", "#1B3A5C" in html and "Sansiri News" in html, "main banner present")
    # C5 section headers
    chk("C5", "ข่าวกลุ่มบริษัทแสนสิริ" in html and "ข่าวคู่แข่งและอสังหาทั่วไป" in html,
        "both section headers present")
    # C6 footer exact
    chk("C6", FOOTER in html and FOOTER2 in html, "footer text correct")
    # C7 headline anchors unstyled (no underline on bold black headline anchors)
    bad_anchor = re.search(r'<a[^>]*color:#000000;text-decoration:underline', html)
    chk("C7", bad_anchor is None, "headline anchors not underlined")
    # C8 each item has >=1 source link (count source-link paragraphs vs headline paragraphs)
    headlines = len(re.findall(r'text-decoration:none;font-weight:bold;">', html))
    linkrows = len(re.findall(r'color:#0563C1;text-decoration:underline;', html))
    chk("C8", headlines == 0 or linkrows >= headlines, "every item has source links")
    # C9 item count == 10 (warning unless --strict-count)
    chk("C9", headlines == 10,
        f"item count = {headlines} (expected 10)", warn=not strict_count)
    # C10 Links resolve directly: online/social must NOT keep the Dataxet proxy
    # wrapper; only print-clipping PDFs may keep re.dataxet.co/api/.
    hrefs = re.findall(r'href="([^"]+)"', html)
    wrapped = [u for u in hrefs if "re.dataxet.co/api/" in u
               and "iqnewsclip.com/reportdl/printdl" not in u]
    chk("C10", not wrapped,
        f"online/social links unwrapped to direct URLs (still wrapped: {len(wrapped)})")
    # C11 no style block
    chk("C11", "<style" not in html.lower(), "no <style> block")
    # C12 no Noto Sans Thai
    chk("C12", "noto sans thai" not in html.lower(), "no Noto Sans Thai font")
    # C13 banner bgcolor attrs present (so navy/gold survive clients that strip
    # CSS background-color — guards the "invisible white title" regression)
    chk("C13", 'bgcolor="#D4A843"' in html and 'bgcolor="#1B3A5C"' in html,
        "banner bgcolor attributes present (gold + navy)")
    # C14 email body carries no google.com/url wrapper (our hrefs must be clean;
    # Gmail adds its own wrapper at display — it must never be in our source)
    chk("C14", "google.com/url" not in html,
        "no google.com/url wrapper baked into source")
    return results


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("html_file")
    ap.add_argument("--strict-count", action="store_true")
    args = ap.parse_args()

    with open(args.html_file, encoding="utf-8") as fh:
        html = fh.read()

    results = run_checks(html, strict_count=args.strict_count)
    failures = warnings = 0
    for cid, ok, warn, msg in results:
        if ok:
            print(f"  ✅ {cid} — {msg}")
        elif warn:
            print(f"  ⚠️  {cid} — {msg}")
            warnings += 1
        else:
            print(f"  ❌ {cid} — {msg}")
            failures += 1
    print(f"\n📊 {failures} failure(s), {warnings} warning(s)")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
